// ─────────────────────────────────────────────────────────────────────────────
// Creator Intelligence — Knowledge Registry: Archetypes (Sprint FYV-3.4A)
//
// Baseline strategic knowledge for all 29 creator archetypes.
//
// The map is typed as Record<CreatorArchetype, ArchetypeKnowledge>, so the
// TypeScript compiler ENFORCES that every member of CREATOR_ARCHETYPES has an
// entry — a missing or misspelled archetype fails `npm run typecheck`.
//
// Content is positioning/coaching strategy only: audience psychology, content
// cadence, monetisation levers, and growth risks. It is intentionally
// non-explicit and platform-neutral.
// ─────────────────────────────────────────────────────────────────────────────

import type { CreatorArchetype } from '@/types/creator';
import type { ArchetypeKnowledge } from './types';

export const ARCHETYPE_KNOWLEDGE: Record<CreatorArchetype, ArchetypeKnowledge> = {
  'Girl Next Door': {
    archetype: 'Girl Next Door',
    identity: 'The warm, attainable everyday partner — charm and authenticity over spectacle.',
    strengths: ['Natural relatability', 'Fast parasocial trust', 'Low-production sustainability', 'Broad mainstream appeal'],
    weaknesses: ['Easily commoditised', 'Tends to under-price', 'Can feel "too available" to command premiums'],
    audience: 'Fans seeking comfort, familiarity, and genuine connection rather than fantasy spectacle.',
    communicationStyle: 'Warm, conversational, and personal — like texting a close friend.',
    monetisationStrengths: ['Strong subscription retention', 'Relationship-driven tips', 'Warm DM and bundle upsells'],
    contentStyles: ['Day-in-the-life and GRWM', 'Casual check-ins', 'Conversational DMs', 'Relatable storytimes'],
    growthRisks: ['Saturation in a crowded lane', 'Boundary creep from over-familiarity', 'Plateau without a sharper hook'],
    coachingRecommendations: ['Define a signature hook beyond "relatable"', 'Hold firm pricing and boundaries', 'Add one recurring premium format'],
    confidenceNotes: 'High-confidence default; frequently self-selected, so validate with tone and authenticity signals, not persona choice alone.',
  },
  'Hot Teacher': {
    archetype: 'Hot Teacher',
    identity: 'Approachable authority — knowledgeable, in-control, with a playful forbidden edge.',
    strengths: ['Authority and credibility', 'Clear roleplay hook', 'Strong custom-content fit', 'Articulate communication'],
    weaknesses: ['Persona can feel scripted if overplayed', 'Narrower than lifestyle archetypes', 'Needs consistent character upkeep'],
    audience: 'Fans drawn to confident expertise and a structured authority-figure dynamic.',
    communicationStyle: 'Composed and instructive with warmth — guiding rather than performing.',
    monetisationStrengths: ['Premium custom requests', 'Themed PPV series', 'Tiered "lessons" framing'],
    contentStyles: ['Scenario-led roleplay', 'Themed series', 'Q&A and "office hours" formats', 'Character-consistent sets'],
    growthRisks: ['Character fatigue', 'Over-reliance on a single trope', 'Difficulty pivoting personas'],
    coachingRecommendations: ['Build a repeatable scenario library', 'Vary intensity to avoid fatigue', 'Anchor pricing to the authority premium'],
    confidenceNotes: 'Moderate confidence; strongest when paired with roleplay or authority signals in the assessment.',
  },
  'Naughty Librarian': {
    archetype: 'Naughty Librarian',
    identity: 'The reserved-then-surprising persona — quiet intellect with a hidden playful side.',
    strengths: ['Strong reveal/contrast hook', 'Intellectual appeal', 'Niche loyalty', 'Memorable positioning'],
    weaknesses: ['Subtle brand can read as low-energy', 'Narrow appeal', 'Hard to scale to mass reach'],
    audience: 'Fans who enjoy the tension between restraint and reveal, and value intelligence as part of the draw.',
    communicationStyle: 'Measured, witty, and understated — rewarding attention with payoff.',
    monetisationStrengths: ['Anticipation-led PPV', 'Loyal core subscribers', 'Story-driven custom content'],
    contentStyles: ['Slow-burn reveal sets', 'Witty captions and storytelling', 'Themed "after hours" content'],
    growthRisks: ['Low-energy perception', 'Slow top-of-funnel growth', 'Trope becoming one-note'],
    coachingRecommendations: ['Lead promos with the contrast hook', 'Pair with a livelier secondary format', 'Invest in caption craft'],
    confidenceNotes: 'Lower-frequency archetype; treat as moderate confidence and confirm with positioning keywords.',
  },
  'Nurse': {
    archetype: 'Nurse',
    identity: 'The nurturing caregiver — comforting, attentive authority with a service warmth.',
    strengths: ['High parasocial warmth', 'Caregiver fantasy fit', 'Strong DM connection', 'Trust-led retention'],
    weaknesses: ['Emotional labour heavy', 'Boundary risk from over-caring', 'Persona upkeep required'],
    audience: 'Fans seeking comfort, attention, and a sense of being cared for.',
    communicationStyle: 'Soothing, attentive, and reassuring — checking in and remembering details.',
    monetisationStrengths: ['Personalised check-in upsells', 'Custom comfort content', 'High-loyalty subscriptions'],
    contentStyles: ['Caregiver roleplay', 'Personalised messages', 'Comfort and reassurance themes'],
    growthRisks: ['Emotional burnout', 'Dependency dynamics with fans', 'Boundary erosion'],
    coachingRecommendations: ['Set explicit emotional boundaries', 'Template repeatable check-ins', 'Price emotional labour appropriately'],
    confidenceNotes: 'Moderate confidence; strongest when caregiving and warmth signals co-occur.',
  },
  'Doctor': {
    archetype: 'Doctor',
    identity: 'Premium clinical authority — polished, confident, and aspirational expertise.',
    strengths: ['Premium positioning', 'Authority credibility', 'Clear roleplay structure', 'Justifies higher pricing'],
    weaknesses: ['Can feel cold without warmth', 'Narrow niche', 'High production expectations'],
    audience: 'Fans attracted to confident, high-status expertise and a premium authority dynamic.',
    communicationStyle: 'Precise, confident, and composed — authoritative but personable.',
    monetisationStrengths: ['Premium tier pricing', 'Bespoke "consultation" customs', 'Exclusive PPV'],
    contentStyles: ['Authority roleplay', 'Polished themed sets', 'Premium custom requests'],
    growthRisks: ['Perceived coldness', 'High production burden', 'Limited mass appeal'],
    coachingRecommendations: ['Balance authority with warmth', 'Lean into the premium price anchor', 'Keep production consistent'],
    confidenceNotes: 'Moderate confidence; pairs with authority/premium signals and rarely self-selected casually.',
  },
  'Corporate Rebel': {
    archetype: 'Corporate Rebel',
    identity: 'Boss-by-day power inversion — buttoned-up exterior, liberated alter ego.',
    strengths: ['Strong contrast narrative', 'Aspirational + relatable mix', 'Clear story arc', 'Polarising in a good way'],
    weaknesses: ['Narrative needs upkeep', 'Can feel performative', 'Niche appeal'],
    audience: 'Fans drawn to the duality of control and release, and an aspirational professional image.',
    communicationStyle: 'Sharp, confident, and knowing — playing the double-life tension.',
    monetisationStrengths: ['Story-arc PPV series', 'Premium "after-hours" framing', 'Strong tip events'],
    contentStyles: ['Double-life storytelling', 'Themed transformation sets', 'Episodic series'],
    growthRisks: ['Narrative fatigue', 'Performative drift', 'Hard to sustain duality'],
    coachingRecommendations: ['Treat content as an episodic arc', 'Refresh the narrative regularly', 'Anchor on the contrast hook'],
    confidenceNotes: 'Lower-frequency; moderate confidence, validate with professional/duality positioning.',
  },
  'Fitness Goddess': {
    archetype: 'Fitness Goddess',
    identity: 'Aspirational body and discipline — health, strength, and visual confidence.',
    strengths: ['Cross-platform funnel potential', 'Visual discipline', 'Aspirational brand', 'Repeatable formats'],
    weaknesses: ['High content-production load', 'Comparison pressure', 'Platform de-platforming risk on mainstream'],
    audience: 'Fans inspired by physique, routine, and aspirational health and confidence.',
    communicationStyle: 'Motivational and confident — coach-like encouragement.',
    monetisationStrengths: ['Programs and guides', 'Cross-platform top-of-funnel', 'Premium body-focused PPV'],
    contentStyles: ['Workout and progress content', 'Transformation arcs', 'Routine and discipline themes'],
    growthRisks: ['Burnout from production cadence', 'Comparison and body pressure', 'Mainstream account bans'],
    coachingRecommendations: ['Build a mainstream funnel safely', 'Systematise filming batches', 'Diversify beyond body-only content'],
    confidenceNotes: 'High confidence when fitness niche/strength signals are present; strongly validated by assessment metadata.',
  },
  'Dominatrix': {
    archetype: 'Dominatrix',
    identity: 'Power and control — commanding presence and premium dominance dynamics.',
    strengths: ['Premium pricing power', 'Distinct, defensible niche', 'High custom-content value', 'Strong fan loyalty'],
    weaknesses: ['Polarising reach', 'Persona discipline demanding', 'Boundary and safety vigilance required'],
    audience: 'Fans seeking submission, structure, and an intense power dynamic.',
    communicationStyle: 'Commanding, deliberate, and boundary-led — control is the product.',
    monetisationStrengths: ['High-value customs and tributes', 'Premium subscription tier', 'Tasking and structured offers'],
    contentStyles: ['Power-dynamic roleplay', 'Tasking and instruction', 'Premium custom sessions'],
    growthRisks: ['Narrow top-of-funnel', 'Boundary-pushing fans', 'Burnout from intensity'],
    coachingRecommendations: ['Codify boundaries and screening', 'Anchor premium pricing confidently', 'Build a tribute/task framework'],
    confidenceNotes: 'High confidence; rarely chosen casually and strongly signalled by dominance positioning.',
  },
  'Brat': {
    archetype: 'Brat',
    identity: 'Playful defiance — cheeky, teasing, push-and-pull energy.',
    strengths: ['High-energy engagement', 'Strong banter and DMs', 'Memorable personality', 'Fun, shareable tone'],
    weaknesses: ['Can read as abrasive', 'Energy is tiring to sustain', 'Boundary clarity needed'],
    audience: 'Fans who enjoy playful challenge, banter, and a teasing dynamic.',
    communicationStyle: 'Cheeky, quick, and teasing — provocative but playful.',
    monetisationStrengths: ['Banter-driven tips', 'Game/challenge monetisation', 'Engaged DM upsells'],
    contentStyles: ['Teasing and challenge content', 'Interactive games', 'Playful callouts'],
    growthRisks: ['Tone misread as hostile', 'Energy burnout', 'Fan friction'],
    coachingRecommendations: ['Keep teasing affectionate, not alienating', 'Use games to channel energy', 'Set clear playful boundaries'],
    confidenceNotes: 'Moderate confidence; pairs with high social energy and playful positioning signals.',
  },
  'Submissive': {
    archetype: 'Submissive',
    identity: 'Yielding and service-led — softness, devotion, and responsiveness.',
    strengths: ['Strong intimacy hook', 'High custom-content fit', 'Loyal niche', 'Clear dynamic'],
    weaknesses: ['Boundary and safety risk', 'Emotional labour heavy', 'Can attract entitlement'],
    audience: 'Fans seeking a caretaking or dominant role and a responsive, devoted dynamic.',
    communicationStyle: 'Soft, attentive, and accommodating — within firmly held limits.',
    monetisationStrengths: ['Personalised customs', 'Devotion-led tips', 'Loyal subscriptions'],
    contentStyles: ['Responsive roleplay', 'Personalised messages', 'Service-dynamic themes'],
    growthRisks: ['Boundary erosion', 'Emotional burnout', 'Entitled fan behaviour'],
    coachingRecommendations: ['Hold non-negotiable boundaries', 'Screen and template requests', 'Price emotional/custom labour fairly'],
    confidenceNotes: 'Moderate confidence; verify with explicit dynamic signals and pair with boundary coaching.',
  },
  'Trophy Wife': {
    archetype: 'Trophy Wife',
    identity: 'Pampered luxury domesticity — refined, indulgent, aspirational comfort.',
    strengths: ['Aspirational lifestyle brand', 'Premium aesthetic', 'Clear fantasy', 'Strong visual identity'],
    weaknesses: ['High production/styling cost', 'Narrow lifestyle lane', 'Authenticity scrutiny'],
    audience: 'Fans drawn to luxury, indulgence, and an aspirational partner fantasy.',
    communicationStyle: 'Polished, indulgent, and gracious — luxury as lifestyle.',
    monetisationStrengths: ['Premium subscription', 'Luxury lifestyle PPV', 'Gifting and wishlist culture'],
    contentStyles: ['Luxury lifestyle sets', 'Styled at-home content', 'Aspirational vignettes'],
    growthRisks: ['Production cost creep', 'Authenticity doubts', 'Lifestyle fatigue'],
    coachingRecommendations: ['Lean into gifting/wishlist mechanics', 'Keep styling consistent but efficient', 'Tell a believable lifestyle story'],
    confidenceNotes: 'Moderate confidence; validate with luxury/lifestyle positioning keywords.',
  },
  'Rich Girl': {
    archetype: 'Rich Girl',
    identity: 'Effortless wealth and exclusivity — aspirational, slightly unattainable glamour.',
    strengths: ['Exclusivity hook', 'Premium positioning', 'Aspirational appeal', 'Strong brand aesthetic'],
    weaknesses: ['Unattainability can limit warmth', 'High aesthetic upkeep', 'Authenticity scrutiny'],
    audience: 'Fans attracted to status, exclusivity, and an aspirational lifestyle.',
    communicationStyle: 'Confident, exclusive, and selectively warm — access feels earned.',
    monetisationStrengths: ['Premium tiers', 'Exclusivity-led upsells', 'Gifting culture'],
    contentStyles: ['Luxury lifestyle content', 'Exclusive "VIP" framing', 'Aspirational styling'],
    growthRisks: ['Perceived coldness', 'Aesthetic cost', 'Believability gaps'],
    coachingRecommendations: ['Balance exclusivity with selective access', 'Use VIP tiers deliberately', 'Keep the lifestyle credible'],
    confidenceNotes: 'Moderate confidence; closely related to Trophy Wife and Luxury Muse — disambiguate with tone.',
  },
  'Luxury Muse': {
    archetype: 'Luxury Muse',
    identity: 'High-fashion editorial elegance — artful, polished, aspirational beauty.',
    strengths: ['Editorial visual quality', 'Premium brand', 'High custom value', 'Cross-over fashion appeal'],
    weaknesses: ['High production demands', 'Can feel distant', 'Slower top-of-funnel'],
    audience: 'Fans who value beauty, polish, and an aspirational, curated aesthetic.',
    communicationStyle: 'Refined and tasteful — elegance over explicitness.',
    monetisationStrengths: ['Premium pricing', 'Editorial PPV sets', 'Bespoke high-value customs'],
    contentStyles: ['High-fashion shoots', 'Editorial themed sets', 'Curated aesthetic content'],
    growthRisks: ['Production cost and time', 'Emotional distance from fans', 'Niche reach'],
    coachingRecommendations: ['Protect the premium with quality', 'Add warmth via DMs/behind-the-scenes', 'Batch editorial production'],
    confidenceNotes: 'High confidence when high-fashion signals present; strongly validated by niche metadata.',
  },
  'Alternative / Tattooed': {
    archetype: 'Alternative / Tattooed',
    identity: 'Subculture edge — alt aesthetic, ink, and authentic counter-culture identity.',
    strengths: ['Devoted niche loyalty', 'Strong differentiation', 'Authentic identity', 'Community belonging'],
    weaknesses: ['Niche ceiling on mass reach', 'Aesthetic upkeep', 'Subculture credibility scrutiny'],
    audience: 'Fans who identify with alternative culture and seek authenticity and edge.',
    communicationStyle: 'Authentic, expressive, and community-minded — belonging over polish.',
    monetisationStrengths: ['Loyal subscriber base', 'Community-led tips', 'Niche custom content'],
    contentStyles: ['Alt-aesthetic sets', 'Tattoo and style showcases', 'Subculture lifestyle content'],
    growthRisks: ['Reach plateau', 'Inauthenticity backlash', 'Over-niching'],
    coachingRecommendations: ['Double down on authentic identity', 'Cultivate community rituals', 'Selectively broaden aesthetic'],
    confidenceNotes: 'Moderate-to-high confidence when alt/tattoo niche signals are present.',
  },
  'Gamer Girl': {
    archetype: 'Gamer Girl',
    identity: 'Relatable gaming culture — playful nerd energy and community connection.',
    strengths: ['Built-in community/culture', 'Cross-platform funnel (streaming)', 'High relatability', 'Strong engagement'],
    weaknesses: ['Audience can be low-spend', 'Time-heavy streaming', 'Credibility scrutiny in gaming culture'],
    audience: 'Fans who share gaming interests and want a relatable, community-driven connection.',
    communicationStyle: 'Casual, playful, and community-native — banter and shared references.',
    monetisationStrengths: ['Streaming-to-subscription funnel', 'Community tips/subs', 'Themed gaming content'],
    contentStyles: ['Gaming + lifestyle blend', 'Stream highlights', 'Cosplay/character crossovers'],
    growthRisks: ['Low average spend', 'Time burnout from streaming', 'Niche gatekeeping'],
    coachingRecommendations: ['Convert free community to paid deliberately', 'Bundle gaming + premium content', 'Protect time with batching'],
    confidenceNotes: 'Moderate confidence; pairs with gaming niche signals and cross-platform presence.',
  },
  'Cosplayer': {
    archetype: 'Cosplayer',
    identity: 'Craft-driven character fantasy — fandom, costume artistry, and transformation.',
    strengths: ['Fandom-driven demand', 'High craft differentiation', 'Strong custom potential', 'Shareable visuals'],
    weaknesses: ['High costume/production cost', 'IP and platform risk', 'Time-intensive'],
    audience: 'Fans of specific fandoms and character fantasies who value craft and accuracy.',
    communicationStyle: 'Enthusiastic and fandom-fluent — shared love of the source material.',
    monetisationStrengths: ['Character-specific customs', 'Set-based PPV', 'Fandom event tie-ins'],
    contentStyles: ['Character cosplay sets', 'Transformation content', 'Fandom-themed series'],
    growthRisks: ['Production cost vs. return', 'IP takedowns', 'Burnout from build time'],
    coachingRecommendations: ['Prioritise high-demand characters', 'Reuse builds across formats', 'Manage IP exposure'],
    confidenceNotes: 'Moderate-to-high confidence when cosplay/roleplay niche signals are present.',
  },
  'Spiritual Goddess': {
    archetype: 'Spiritual Goddess',
    identity: 'Ethereal mystic wellness — sensual spirituality, calm, and aspiration.',
    strengths: ['Distinct, calming brand', 'Wellness crossover', 'Loyal values-aligned fans', 'Differentiated tone'],
    weaknesses: ['Niche appeal', 'Authenticity scrutiny', 'Harder explicit-content fit'],
    audience: 'Fans drawn to mystique, calm, sensual spirituality, and aspirational wellness.',
    communicationStyle: 'Serene, affirming, and intentional — presence over performance.',
    monetisationStrengths: ['Wellness/ritual content', 'Premium calm-aesthetic PPV', 'Values-aligned community'],
    contentStyles: ['Sensual wellness content', 'Ritual and aesthetic sets', 'Affirmation and lifestyle'],
    growthRisks: ['Limited reach', 'Tone/explicitness mismatch', 'Credibility doubts'],
    coachingRecommendations: ['Hold a consistent serene brand', 'Clarify the content/wellness balance', 'Lean into values-aligned community'],
    confidenceNotes: 'Lower-frequency archetype; moderate confidence, confirm with wellness/aesthetic positioning.',
  },
  'MILF': {
    archetype: 'MILF',
    identity: 'Mature confidence — experience, self-assurance, and grounded allure.',
    strengths: ['Confident, defined brand', 'Strong loyal demographic', 'Authenticity advantage', 'Premium maturity angle'],
    weaknesses: ['Age-targeting discovery friction', 'Comparison pressure', 'Stereotype constraints'],
    audience: 'Fans who value maturity, confidence, and experienced, grounded connection.',
    communicationStyle: 'Confident, direct, and self-assured — comfortable in her own skin.',
    monetisationStrengths: ['Loyal premium subscribers', 'Experience-led customs', 'Strong retention'],
    contentStyles: ['Confident lifestyle content', 'Experience-led themes', 'Authentic personal sets'],
    growthRisks: ['Discovery/algorithm friction', 'Stereotype boxing', 'Comparison pressure'],
    coachingRecommendations: ['Lead with confidence as the brand', 'Avoid one-note stereotyping', 'Cultivate loyal-core retention'],
    confidenceNotes: 'Moderate confidence; validate with maturity positioning rather than assuming from demographics.',
  },
  'Single Mom': {
    archetype: 'Single Mom',
    identity: 'Real-life relatability — authentic, resilient, and down-to-earth.',
    strengths: ['High authenticity', 'Strong parasocial empathy', 'Relatable narrative', 'Loyal supportive fans'],
    weaknesses: ['Privacy/safety exposure', 'Time and energy constraints', 'Boundary management'],
    audience: 'Fans who connect with realness, resilience, and a supportive, rooting-for-you dynamic.',
    communicationStyle: 'Honest, warm, and grounded — real life shared selectively.',
    monetisationStrengths: ['Loyalty-driven subscriptions', 'Supportive tip culture', 'Relatable storytelling upsells'],
    contentStyles: ['Authentic lifestyle content', 'Relatable storytimes', 'Behind-the-scenes realness'],
    growthRisks: ['Privacy exposure', 'Time scarcity', 'Emotional over-sharing'],
    coachingRecommendations: ['Protect privacy and identity', 'Template content to save time', 'Guard against over-disclosure'],
    confidenceNotes: 'Moderate confidence; treat sensitively and confirm with authenticity/lifestyle signals.',
  },
  'College Girl': {
    archetype: 'College Girl',
    identity: 'Youthful peer energy — fresh, fun, and relatable to a younger sensibility.',
    strengths: ['High relatability', 'Energetic content', 'Trend-native', 'Strong social-funnel fit'],
    weaknesses: ['Lower average spend', 'Trend dependence', 'Compliance/verification scrutiny'],
    audience: 'Fans drawn to youthful energy, relatability, and a peer-like dynamic.',
    communicationStyle: 'Bubbly, casual, and trend-fluent — fun and approachable.',
    monetisationStrengths: ['Social-to-sub funnel', 'Trend-driven content drops', 'Volume engagement'],
    contentStyles: ['Trend-led content', 'Casual lifestyle', 'Playful relatable sets'],
    growthRisks: ['Low spend per fan', 'Trend churn', 'Heightened compliance scrutiny'],
    coachingRecommendations: ['Convert social reach to paid', 'Avoid over-reliance on trends', 'Keep verification/compliance airtight'],
    confidenceNotes: 'Moderate confidence; emphasise compliance and validate with energy/relatability signals.',
  },
  'Party Girl': {
    archetype: 'Party Girl',
    identity: 'Nightlife and high-energy fun — spontaneous, social, and magnetic.',
    strengths: ['High visibility energy', 'Strong social content', 'Magnetic personality', 'Shareable moments'],
    weaknesses: ['Sustainability/burnout risk', 'Lifestyle scrutiny', 'Boundary blur in public content'],
    audience: 'Fans drawn to excitement, spontaneity, and vicarious nightlife energy.',
    communicationStyle: 'High-energy, spontaneous, and flirty — the life of the party.',
    monetisationStrengths: ['Event-led content drops', 'Tip-driven live moments', 'Social-funnel volume'],
    contentStyles: ['Nightlife and event content', 'High-energy social posts', 'Spontaneous live formats'],
    growthRisks: ['Burnout and sustainability', 'Lifestyle-cost creep', 'Public boundary issues'],
    coachingRecommendations: ['Make the lifestyle sustainable', 'Channel energy into scheduled drops', 'Protect privacy in public content'],
    confidenceNotes: 'Moderate-to-high confidence when nightlife/high-energy signals are present.',
  },
  'Boss Babe': {
    archetype: 'Boss Babe',
    identity: 'Entrepreneurial control — ambitious, aspirational, and in command of her brand.',
    strengths: ['Aspirational brand', 'Business-minded operations', 'Premium positioning', 'Cross-sell potential'],
    weaknesses: ['Can feel transactional', 'Warmth needs deliberate effort', 'Self-managed overload'],
    audience: 'Fans who admire ambition, control, and an aspirational, self-made image.',
    communicationStyle: 'Confident, direct, and motivational — in control and on-brand.',
    monetisationStrengths: ['Premium tiers and bundles', 'Strong upsell discipline', 'Brand/merch crossover'],
    contentStyles: ['Aspirational lifestyle', 'Behind-the-brand content', 'Premium themed sets'],
    growthRisks: ['Transactional perception', 'Operational overload', 'Connection deficit'],
    coachingRecommendations: ['Add intentional warmth and connection', 'Systematise operations', 'Use tiers to anchor premium value'],
    confidenceNotes: 'Moderate confidence; pairs with ambition/business motivation signals.',
  },
  'Country Girl': {
    archetype: 'Country Girl',
    identity: 'Wholesome, outdoorsy charm — down-to-earth, natural, and genuine.',
    strengths: ['Authentic, warm brand', 'Differentiated aesthetic', 'Loyal niche', 'Relatable charm'],
    weaknesses: ['Niche reach', 'Aesthetic consistency needed', 'Lower trend velocity'],
    audience: 'Fans drawn to wholesome, natural, down-to-earth charm and authenticity.',
    communicationStyle: 'Warm, genuine, and easy-going — neighbourly and sincere.',
    monetisationStrengths: ['Loyal subscriber retention', 'Authentic lifestyle PPV', 'Warm tip culture'],
    contentStyles: ['Outdoor and lifestyle content', 'Natural aesthetic sets', 'Relatable storytelling'],
    growthRisks: ['Limited reach', 'Aesthetic monotony', 'Slow growth'],
    coachingRecommendations: ['Lean into authentic charm', 'Vary settings to stay fresh', 'Build a loyal-core strategy'],
    confidenceNotes: 'Lower-frequency archetype; moderate confidence, confirm with lifestyle/aesthetic signals.',
  },
  'Bimbo': {
    archetype: 'Bimbo',
    identity: 'Hyper-glam playful exaggeration — bold aesthetic and unapologetic fun.',
    strengths: ['Bold, memorable aesthetic', 'Clear fantasy', 'Strong visual identity', 'Playful tone'],
    weaknesses: ['Polarising', 'High glam upkeep', 'Stereotype constraints'],
    audience: 'Fans who enjoy bold glamour, playful exaggeration, and an unapologetic fantasy.',
    communicationStyle: 'Playful, exaggerated, and confident — leaning into the persona with fun.',
    monetisationStrengths: ['Distinct premium aesthetic', 'Themed PPV', 'Strong brand merch fit'],
    contentStyles: ['Hyper-glam sets', 'Playful themed content', 'Bold aesthetic visuals'],
    growthRisks: ['Polarised reach', 'Glam cost creep', 'One-note persona'],
    coachingRecommendations: ['Own the aesthetic confidently', 'Add personality depth beyond the look', 'Control production cost'],
    confidenceNotes: 'Moderate confidence; validate with glam/playful positioning keywords.',
  },
  'Soft Girlfriend Experience': {
    archetype: 'Soft Girlfriend Experience',
    identity: 'Intimate companionship — tenderness, attentiveness, and a real-feeling bond.',
    strengths: ['Deep parasocial bonds', 'Very high retention', 'Strong DM monetisation', 'Premium intimacy value'],
    weaknesses: ['Heavy emotional labour', 'Boundary risk', 'Hard to scale 1:1 intimacy'],
    audience: 'Fans seeking emotional intimacy, companionship, and a girlfriend-like connection.',
    communicationStyle: 'Tender, attentive, and personal — making each fan feel uniquely seen.',
    monetisationStrengths: ['High-LTV subscriptions', 'Personalised DM upsells', 'Custom intimate content'],
    contentStyles: ['Personalised messages', 'Intimate everyday content', 'Companion-style updates'],
    growthRisks: ['Emotional burnout', 'Dependency dynamics', 'Scaling limits on personal attention'],
    coachingRecommendations: ['Set sustainable DM boundaries', 'Use chat tooling/templates to scale care', 'Price intimacy and time properly'],
    confidenceNotes: 'High confidence when connection/intimacy signals are strong; central to retention strategy.',
  },
  'High-Class Escort Fantasy': {
    archetype: 'High-Class Escort Fantasy',
    identity: 'Elite exclusivity — refined, premium, and aspirational companionship fantasy.',
    strengths: ['Top-tier premium pricing', 'Exclusivity hook', 'High custom value', 'Strong brand prestige'],
    weaknesses: ['Polarising and scrutiny-prone', 'High aesthetic/production bar', 'Compliance sensitivity'],
    audience: 'Fans seeking an exclusive, premium, refined companionship fantasy.',
    communicationStyle: 'Polished, discreet, and exclusive — access is the privilege.',
    monetisationStrengths: ['Premium top tiers', 'Bespoke high-value customs', 'Exclusivity-led upsells'],
    contentStyles: ['Refined premium sets', 'Exclusive VIP framing', 'Aspirational companionship themes'],
    growthRisks: ['Compliance and platform scrutiny', 'Narrow reach', 'Production cost'],
    coachingRecommendations: ['Keep messaging compliant and fantasy-framed', 'Protect the premium with quality', 'Use scarcity deliberately'],
    confidenceNotes: 'High confidence; rarely casual, but coach carefully on compliant, fantasy-framed positioning.',
  },
  'Seductress': {
    archetype: 'Seductress',
    identity: 'Classic allure and tease mastery — confident, magnetic, anticipation-driven.',
    strengths: ['Timeless broad appeal', 'Strong tease-to-paid funnel', 'Confident brand', 'Flexible positioning'],
    weaknesses: ['Less differentiated', 'Relies on execution quality', 'Can feel generic without a hook'],
    audience: 'Fans drawn to confident allure, anticipation, and classic seduction.',
    communicationStyle: 'Confident, alluring, and unhurried — mastery of anticipation.',
    monetisationStrengths: ['Tease-and-reveal PPV funnel', 'Strong conversion mechanics', 'Bundle upsells'],
    contentStyles: ['Tease-and-reveal sets', 'Anticipation-led series', 'Confident signature visuals'],
    growthRisks: ['Lack of differentiation', 'Execution dependence', 'Generic positioning'],
    coachingRecommendations: ['Add a distinct signature hook', 'Master the tease-to-paid funnel', 'Invest in execution quality'],
    confidenceNotes: 'Moderate confidence; common fallback positioning, so confirm with a differentiating signal.',
  },
  'Artist / Creative Muse': {
    archetype: 'Artist / Creative Muse',
    identity: 'Creative self-expression — artistry, aesthetic vision, and authentic craft.',
    strengths: ['Distinct creative brand', 'Cross-over (art/fashion) appeal', 'Authentic differentiation', 'Story-rich content'],
    weaknesses: ['Monetisation can lag artistry', 'Niche reach', 'Production time-heavy'],
    audience: 'Fans who value creativity, aesthetic vision, and an authentic artistic identity.',
    communicationStyle: 'Expressive, thoughtful, and aesthetic-led — sharing the creative process.',
    monetisationStrengths: ['Premium artistic sets', 'Process/behind-the-art upsells', 'Collectible/limited drops'],
    contentStyles: ['Artistic themed shoots', 'Creative process content', 'Aesthetic storytelling'],
    growthRisks: ['Art-over-monetisation imbalance', 'Reach plateau', 'Production overhead'],
    coachingRecommendations: ['Connect artistry to clear offers', 'Sell the process, not just the output', 'Batch creative production'],
    confidenceNotes: 'Moderate confidence; validate with creative/aesthetic positioning signals.',
  },
  'Other': {
    archetype: 'Other',
    identity: 'Uncategorised or emerging positioning — no dominant archetype yet identified.',
    strengths: ['Open positioning', 'Flexibility to test directions', 'No stereotype constraints'],
    weaknesses: ['Unclear hook', 'Weak discoverability', 'Harder to coach without a direction'],
    audience: 'Not yet well defined — audience clarity is the first objective.',
    communicationStyle: 'To be established — start authentic and observe what resonates.',
    monetisationStrengths: ['Freedom to test offers', 'Can adopt proven adjacent playbooks'],
    contentStyles: ['Exploratory content tests', 'A/B of formats and tones', 'Authentic baseline content'],
    growthRisks: ['Lack of positioning', 'Slow traction', 'Scattered effort'],
    coachingRecommendations: ['Run structured positioning discovery', 'Test two or three adjacent archetypes', 'Commit once a hook resonates'],
    confidenceNotes: 'Neutral fallback used when no archetype is identified; treat as low confidence and prioritise discovery.',
  },
};

/**
 * Safe fallback for unknown / unmapped archetypes.
 * Reuses the neutral 'Other' profile, which is guaranteed to exist by the
 * Record<CreatorArchetype, …> type above.
 */
export const FALLBACK_ARCHETYPE_KNOWLEDGE: ArchetypeKnowledge = ARCHETYPE_KNOWLEDGE['Other'];

/** Convenience accessor used by the registry layer. */
export function archetypeKnowledgeFor(archetype: CreatorArchetype): ArchetypeKnowledge {
  return ARCHETYPE_KNOWLEDGE[archetype];
}
