// ─────────────────────────────────────────────────────────────────────────────
// Creator Intelligence — Knowledge Registry: Recommendations (Sprint FYV-3.4B)
//
// Structured coaching/strategy recommendation catalogue.
// 22 entries, each tagged by applicable archetypes, verticals, audiences,
// traits, priority, impact, and difficulty.
//
// An empty applicability array means "universally applicable."
// ─────────────────────────────────────────────────────────────────────────────

import type { Recommendation } from './types';

export const RECOMMENDATIONS: Recommendation[] = [
  // ── Positioning & Brand ───────────────────────────────────────────────────
  {
    id: 'rec-001',
    title: 'Define a signature hook',
    description: 'Identify one distinctive element that separates you from adjacent creators in the same archetype. Pin it across bio, welcome message, and first three pieces of content.',
    applicableArchetypes: ['Girl Next Door', 'Seductress', 'College Girl', 'Party Girl'],
    applicableVerticals: [],
    applicableAudiences: [],
    applicableTraits: ['positioning_clarity'],
    priority: 'high',
    expectedImpact: 'Reduces "who is this?" friction, improving subscribe-through rate by anchoring brand recognition.',
    implementationDifficulty: 'moderate',
    evidenceRequirements: ['Brand clarity score below 65', 'positioning_clarity trait weight below 60'],
    coachingNotes: 'Start with "what would a fan tell a friend about you in one sentence?" and refine from there.',
    reportSummary: 'A sharper positioning hook will help fans understand your promise faster.',
  },
  {
    id: 'rec-002',
    title: 'Build a premium tier with scarcity',
    description: 'Create a limited-access VIP tier with exclusive content, priority DMs, and personalised experiences. Cap membership to sustain exclusivity.',
    applicableArchetypes: ['Luxury Muse', 'Rich Girl', 'Trophy Wife', 'High-Class Escort Fantasy', 'Dominatrix'],
    applicableVerticals: ['Editorial / High-Fashion Shoots', 'Tease & Deny'],
    applicableAudiences: ['whales'],
    applicableTraits: ['monetisation_fit', 'positioning_clarity'],
    priority: 'high',
    expectedImpact: 'Captures high-value fans at premium price points, increasing revenue per subscriber.',
    implementationDifficulty: 'moderate',
    evidenceRequirements: ['Audience strategy is whales', 'Monetisation score above 55'],
    coachingNotes: 'Start with a small cap (10-20 spots), price at 3-5x base, and deliver genuine exclusivity.',
    reportSummary: 'A capped premium tier will monetise your high-value audience strategy effectively.',
  },
  {
    id: 'rec-003',
    title: 'Establish content boundaries early',
    description: 'Document clear lines for what you will and will not create. Communicate these in your welcome message and pin them visibly.',
    applicableArchetypes: ['Submissive', 'Soft Girlfriend Experience', 'Nurse', 'Single Mom'],
    applicableVerticals: ['Confessional Storytime', 'Cosy Authenticity'],
    applicableAudiences: [],
    applicableTraits: ['risk_awareness', 'trust_building'],
    priority: 'critical',
    expectedImpact: 'Prevents boundary erosion, reduces fan conflict, and protects long-term sustainability.',
    implementationDifficulty: 'easy',
    evidenceRequirements: ['risk_awareness trait weight below 55', 'Authenticity band is Potential Conflict or Moderate Authenticity'],
    coachingNotes: 'Frame boundaries as quality commitments, not restrictions. Fans respect clarity.',
    reportSummary: 'Clear boundaries protect your brand and prevent burnout.',
  },
  // ── Content Strategy ──────────────────────────────────────────────────────
  {
    id: 'rec-004',
    title: 'Create a recurring content series',
    description: 'Launch at least one named, recurring content format (e.g., "Monday Check-in", "Friday Reveal") to build habit and anticipation.',
    applicableArchetypes: [],
    applicableVerticals: ['Lifestyle Vlogging / GRWM', 'Cosy Authenticity', 'Polarizing Storytimes', 'Skill-Based Challenges'],
    applicableAudiences: [],
    applicableTraits: ['routine_discipline'],
    priority: 'high',
    expectedImpact: 'Increases retention by giving fans a reason to return on schedule.',
    implementationDifficulty: 'easy',
    evidenceRequirements: ['Consistency score below 60', 'routine_discipline trait weight below 55'],
    coachingNotes: 'Pick a cadence you can sustain for 8+ weeks. Consistency matters more than frequency.',
    reportSummary: 'A recurring series builds fan habit and improves retention.',
  },
  {
    id: 'rec-005',
    title: 'Batch content production',
    description: 'Dedicate 1-2 sessions per week to creating multiple pieces of content, then schedule releases. Reduces daily production burden.',
    applicableArchetypes: ['Fitness Goddess', 'Cosplayer', 'Luxury Muse', 'Artist / Creative Muse'],
    applicableVerticals: ['Editorial / High-Fashion Shoots', 'Fitness Journey', 'Roleplay / Character Content'],
    applicableAudiences: [],
    applicableTraits: ['routine_discipline', 'visual_discipline'],
    priority: 'medium',
    expectedImpact: 'Sustains content cadence without daily filming pressure, reducing burnout risk.',
    implementationDifficulty: 'moderate',
    evidenceRequirements: ['Consistency score below 55'],
    coachingNotes: 'Start with one batch day per week. Use a shot list to stay efficient.',
    reportSummary: 'Batching production will help you stay consistent without daily pressure.',
  },
  {
    id: 'rec-006',
    title: 'Build a tease-to-paid funnel',
    description: 'Structure free content as appetisers that drive fans toward paid reveals, PPV, or premium tiers.',
    applicableArchetypes: ['Seductress', 'Bimbo', 'College Girl', 'Party Girl'],
    applicableVerticals: ['Tease & Deny'],
    applicableAudiences: ['masses'],
    applicableTraits: ['monetisation_fit', 'visibility_comfort'],
    priority: 'high',
    expectedImpact: 'Converts free engagement into revenue by making the transition from free to paid seamless.',
    implementationDifficulty: 'moderate',
    evidenceRequirements: ['Monetisation score below 60', 'Audience strategy is masses'],
    coachingNotes: 'Every free post should have a clear "want more?" pathway. Never give away the payoff.',
    reportSummary: 'A structured tease-to-paid funnel will convert your reach into revenue.',
  },
  {
    id: 'rec-007',
    title: 'Develop a character or scenario library',
    description: 'Build a documented set of recurring characters, scenarios, or themes you can draw on for content and customs.',
    applicableArchetypes: ['Hot Teacher', 'Naughty Librarian', 'Cosplayer', 'Dominatrix', 'Nurse', 'Doctor'],
    applicableVerticals: ['Roleplay / Character Content', 'Comedy Skits'],
    applicableAudiences: [],
    applicableTraits: ['positioning_clarity', 'routine_discipline'],
    priority: 'medium',
    expectedImpact: 'Reduces content-idea fatigue and makes custom requests faster to fulfil.',
    implementationDifficulty: 'moderate',
    evidenceRequirements: ['Archetype involves roleplay or character work'],
    coachingNotes: 'Document 5-8 scenarios with costumes, tone, and storyline notes. Reuse and remix.',
    reportSummary: 'A scenario library makes content production faster and custom requests more profitable.',
  },
  // ── Monetisation ──────────────────────────────────────────────────────────
  {
    id: 'rec-008',
    title: 'Launch a custom content offering',
    description: 'Create a clear, priced menu of custom content options with delivery timelines and boundaries.',
    applicableArchetypes: [],
    applicableVerticals: [],
    applicableAudiences: ['whales'],
    applicableTraits: ['monetisation_fit'],
    priority: 'high',
    expectedImpact: 'Unlocks a high-margin revenue stream with clear expectations on both sides.',
    implementationDifficulty: 'moderate',
    evidenceRequirements: ['Monetisation score below 65', 'monetisation_fit trait weight below 60'],
    coachingNotes: 'Start with 3-5 tiers. Be explicit about what is and is not included. Price for your time.',
    reportSummary: 'A structured custom content menu captures revenue you are currently leaving on the table.',
  },
  {
    id: 'rec-009',
    title: 'Implement strategic pricing tiers',
    description: 'Move from flat pricing to tiered subscription levels that match different fan commitment levels.',
    applicableArchetypes: ['Boss Babe', 'Luxury Muse', 'Dominatrix', 'High-Class Escort Fantasy'],
    applicableVerticals: [],
    applicableAudiences: [],
    applicableTraits: ['monetisation_fit', 'positioning_clarity'],
    priority: 'medium',
    expectedImpact: 'Captures more revenue from committed fans without losing volume subscribers.',
    implementationDifficulty: 'moderate',
    evidenceRequirements: ['Brand clarity score above 55', 'Monetisation readiness is Ready or Advanced'],
    coachingNotes: 'Three tiers is the sweet spot. Name them to match your brand, not generic labels.',
    reportSummary: 'Tiered pricing will capture more value from your most committed fans.',
  },
  {
    id: 'rec-010',
    title: 'Introduce tip-gated interactive content',
    description: 'Use polls, games, and tip-to-unlock mechanics to convert engagement into micro-revenue.',
    applicableArchetypes: ['Brat', 'Party Girl', 'College Girl', 'Gamer Girl'],
    applicableVerticals: ['Skill-Based Challenges', 'Comedy Skits'],
    applicableAudiences: ['masses'],
    applicableTraits: ['social_energy', 'fan_connection'],
    priority: 'medium',
    expectedImpact: 'Monetises high-engagement, lower-spend audiences through volume micro-transactions.',
    implementationDifficulty: 'easy',
    evidenceRequirements: ['Audience strategy is masses', 'social_energy or fan_connection trait weight above 60'],
    coachingNotes: 'Keep tip amounts low ($2-5) and make participation fun, not transactional.',
    reportSummary: 'Interactive tip mechanics will convert your high engagement into revenue.',
  },
  // ── Audience & Community ──────────────────────────────────────────────────
  {
    id: 'rec-011',
    title: 'Build a cross-platform discovery funnel',
    description: 'Establish a presence on 1-2 mainstream platforms specifically to drive traffic to your subscription page.',
    applicableArchetypes: ['Fitness Goddess', 'Gamer Girl', 'College Girl', 'Party Girl', 'Country Girl'],
    applicableVerticals: ['Fitness Journey', 'Lifestyle Vlogging / GRWM', 'Comedy Skits'],
    applicableAudiences: ['masses'],
    applicableTraits: ['visibility_comfort', 'social_energy'],
    priority: 'high',
    expectedImpact: 'Expands top-of-funnel reach beyond the subscription platform, reducing discovery dependence.',
    implementationDifficulty: 'hard',
    evidenceRequirements: ['visibility_comfort trait weight above 60', 'Audience strategy is masses'],
    coachingNotes: 'Choose platforms where your content crosses over safely. Never risk your main account.',
    reportSummary: 'A mainstream discovery funnel will expand your reach beyond the subscription platform.',
  },
  {
    id: 'rec-012',
    title: 'Implement a welcome sequence',
    description: 'Create a 3-5 message automated welcome sequence for new subscribers that builds connection and surfaces your best offers.',
    applicableArchetypes: [],
    applicableVerticals: [],
    applicableAudiences: [],
    applicableTraits: ['fan_connection', 'trust_building'],
    priority: 'high',
    expectedImpact: 'Reduces early churn by establishing value and connection in the critical first 48 hours.',
    implementationDifficulty: 'easy',
    evidenceRequirements: ['fan_connection or trust_building trait weight below 60'],
    coachingNotes: 'Message 1: warm welcome. Message 2: best-of content. Message 3: custom/upgrade offer.',
    reportSummary: 'A welcome sequence reduces early churn and maximises first-week revenue.',
  },
  {
    id: 'rec-013',
    title: 'Personalise high-value fan interactions',
    description: 'Identify top spenders and provide personalised attention — use names, remember preferences, and prioritise responses.',
    applicableArchetypes: ['Soft Girlfriend Experience', 'Nurse', 'Girl Next Door'],
    applicableVerticals: ['Cosy Authenticity', 'Confessional Storytime'],
    applicableAudiences: ['whales'],
    applicableTraits: ['fan_connection', 'trust_building', 'emotional_familiarity'],
    priority: 'high',
    expectedImpact: 'Increases LTV of top fans by strengthening parasocial bonds and justifying premium spend.',
    implementationDifficulty: 'moderate',
    evidenceRequirements: ['Audience strategy is whales', 'fan_connection trait weight above 55'],
    coachingNotes: 'Keep a simple CRM (even a spreadsheet) of top fans and their preferences.',
    reportSummary: 'Personalised attention will deepen loyalty and increase lifetime value from your top fans.',
  },
  // ── Growth & Sustainability ───────────────────────────────────────────────
  {
    id: 'rec-014',
    title: 'Diversify content beyond one format',
    description: 'If you rely on a single content type, introduce at least one complementary format to reduce fatigue and broaden appeal.',
    applicableArchetypes: ['Fitness Goddess', 'Naughty Librarian', 'Spiritual Goddess', 'Country Girl'],
    applicableVerticals: ['Fitness Journey', 'Editorial / High-Fashion Shoots'],
    applicableAudiences: [],
    applicableTraits: ['routine_discipline'],
    priority: 'medium',
    expectedImpact: 'Reduces content monotony, broadens fan appeal, and opens new monetisation paths.',
    implementationDifficulty: 'moderate',
    evidenceRequirements: ['Top verticals cluster on a single format'],
    coachingNotes: 'Add a behind-the-scenes or conversational format alongside your primary visual content.',
    reportSummary: 'Adding a complementary content format will keep fans engaged and open new revenue paths.',
  },
  {
    id: 'rec-015',
    title: 'Set sustainable posting cadence',
    description: 'Determine a realistic posting schedule you can maintain for 90+ days without burnout, then stick to it.',
    applicableArchetypes: [],
    applicableVerticals: [],
    applicableAudiences: [],
    applicableTraits: ['routine_discipline'],
    priority: 'high',
    expectedImpact: 'Prevents the feast-or-famine cycle that causes subscriber churn and creator burnout.',
    implementationDifficulty: 'easy',
    evidenceRequirements: ['Consistency score below 55', 'routine_discipline trait weight below 50'],
    coachingNotes: 'Three quality posts per week beats seven mediocre ones. Quality and consistency over volume.',
    reportSummary: 'A sustainable posting rhythm prevents burnout and keeps subscribers engaged.',
  },
  {
    id: 'rec-016',
    title: 'Develop a 90-day growth plan',
    description: 'Map out three 30-day phases: foundation, experimentation, and scaling. Set measurable targets for each.',
    applicableArchetypes: [],
    applicableVerticals: [],
    applicableAudiences: [],
    applicableTraits: ['coachability'],
    priority: 'medium',
    expectedImpact: 'Provides direction and accountability, preventing scattered effort.',
    implementationDifficulty: 'moderate',
    evidenceRequirements: ['coachability trait weight above 55'],
    coachingNotes: 'Month 1: nail positioning and consistency. Month 2: test monetisation. Month 3: scale what works.',
    reportSummary: 'A structured 90-day plan gives your growth direction and measurable milestones.',
  },
  // ── Emotional & Brand Health ──────────────────────────────────────────────
  {
    id: 'rec-017',
    title: 'Manage parasocial boundaries proactively',
    description: 'Set clear expectations about response times, personal questions, and off-platform contact from the start.',
    applicableArchetypes: ['Soft Girlfriend Experience', 'Submissive', 'Nurse', 'Girl Next Door'],
    applicableVerticals: ['Cosy Authenticity', 'Confessional Storytime'],
    applicableAudiences: ['whales'],
    applicableTraits: ['trust_building', 'risk_awareness', 'fan_connection'],
    priority: 'critical',
    expectedImpact: 'Prevents emotional burnout and unhealthy fan dynamics that threaten sustainability.',
    implementationDifficulty: 'easy',
    evidenceRequirements: ['Fan connection trait weight above 70', 'risk_awareness trait weight below 55'],
    coachingNotes: 'Kind but firm. "I love connecting with you here — this is where I can give you my best."',
    reportSummary: 'Proactive boundary management protects both your wellbeing and your business.',
  },
  {
    id: 'rec-018',
    title: 'Align fantasy positioning with authentic self',
    description: 'Audit where your marketed persona diverges from your authentic comfort zone. Close the gap or own the performance.',
    applicableArchetypes: ['High-Class Escort Fantasy', 'Bimbo', 'Corporate Rebel', 'Dominatrix'],
    applicableVerticals: ['Roleplay / Character Content'],
    applicableAudiences: [],
    applicableTraits: ['authenticity', 'positioning_clarity', 'risk_awareness'],
    priority: 'high',
    expectedImpact: 'Resolves authenticity conflicts that cause inconsistency, fan confusion, and creator discomfort.',
    implementationDifficulty: 'hard',
    evidenceRequirements: ['Authenticity band is Potential Conflict', 'Positioning clarity below 55'],
    coachingNotes: 'Either bring the persona closer to you, or develop the performance skills to sustain the gap.',
    reportSummary: 'Aligning your positioning with your authentic strengths will resolve internal brand conflict.',
  },
  {
    id: 'rec-019',
    title: 'Build camera confidence progressively',
    description: 'Start with low-pressure formats (text, audio, behind-the-scenes) and gradually increase visual exposure as comfort grows.',
    applicableArchetypes: ['Other', 'Single Mom', 'Naughty Librarian', 'Spiritual Goddess'],
    applicableVerticals: ['Cosy Authenticity', 'Confessional Storytime'],
    applicableAudiences: [],
    applicableTraits: ['visibility_comfort'],
    priority: 'high',
    expectedImpact: 'Unlocks visual content formats that drive higher engagement and monetisation.',
    implementationDifficulty: 'moderate',
    evidenceRequirements: ['visibility_comfort trait weight below 45', 'Comfort level below 5'],
    coachingNotes: 'Start with voice notes or faceless content. Each step up should feel like a small stretch, not a leap.',
    reportSummary: 'Progressive camera confidence building will unlock higher-value content formats.',
  },
  // ── Compliance & Safety ───────────────────────────────────────────────────
  {
    id: 'rec-020',
    title: 'Separate personal and creator identity',
    description: 'Use a distinct creator name, separate accounts, and avoid leaking personally identifiable information in content.',
    applicableArchetypes: ['Single Mom', 'College Girl', 'Country Girl', 'Girl Next Door', 'Party Girl', 'Corporate Rebel'],
    applicableVerticals: ['Confessional Storytime', 'Lifestyle Vlogging / GRWM'],
    applicableAudiences: [],
    applicableTraits: ['risk_awareness'],
    priority: 'high',
    expectedImpact: 'Protects personal safety, privacy, and long-term optionality.',
    implementationDifficulty: 'easy',
    evidenceRequirements: ['risk_awareness trait weight below 50'],
    coachingNotes: 'This is non-negotiable for safety. Audit existing content for accidental identity leaks.',
    reportSummary: 'Separating your personal and creator identities is essential for safety.',
  },
  {
    id: 'rec-021',
    title: 'Audit content for platform compliance',
    description: 'Review all published content against current platform terms of service. Remove or archive anything that risks account action.',
    applicableArchetypes: ['College Girl', 'High-Class Escort Fantasy', 'Bimbo'],
    applicableVerticals: [],
    applicableAudiences: [],
    applicableTraits: ['risk_awareness'],
    priority: 'high',
    expectedImpact: 'Reduces deplatforming risk and protects revenue continuity.',
    implementationDifficulty: 'moderate',
    evidenceRequirements: ['Archetype has elevated compliance risk'],
    coachingNotes: 'Focus on bio language, hashtags, and any content that could be misread as violating TOS.',
    reportSummary: 'A compliance audit protects your account and revenue from platform enforcement.',
  },
  {
    id: 'rec-022',
    title: 'Use DM templates for efficiency',
    description: 'Create a library of pre-written DM templates for common interactions — welcome, upsell, boundary, and re-engagement messages.',
    applicableArchetypes: [],
    applicableVerticals: [],
    applicableAudiences: [],
    applicableTraits: ['fan_connection', 'monetisation_fit', 'routine_discipline'],
    priority: 'medium',
    expectedImpact: 'Reduces per-message time cost, enabling higher DM volume without proportional effort.',
    implementationDifficulty: 'easy',
    evidenceRequirements: ['DM monetisation is a primary revenue channel'],
    coachingNotes: 'Templates should feel personal. Use [name] placeholders and keep the tone warm.',
    reportSummary: 'DM templates will help you scale fan interactions without burning out.',
  },
];

/** Recommendation map keyed by id for O(1) lookup. */
export const RECOMMENDATION_MAP: Record<string, Recommendation> = Object.fromEntries(
  RECOMMENDATIONS.map(r => [r.id, r])
);
