// ─────────────────────────────────────────────────────────────────────────────
// Creator Intelligence — Knowledge Registry: Risks (Sprint FYV-3.4B)
//
// Risk definition catalogue. 16 entries, each with severity, detection
// guidance, mitigation, coaching guidance, and related
// archetypes/traits/verticals.
//
// An empty relatedness array means the risk is universally relevant.
// ─────────────────────────────────────────────────────────────────────────────

import type { Risk } from './types';

export const RISKS: Risk[] = [
  // ── Emotional & Personal ──────────────────────────────────────────────────
  {
    id: 'risk-001',
    title: 'Creator burnout',
    description: 'Unsustainable production pace, emotional labour, or boundary erosion leads to exhaustion and content collapse.',
    severity: 'high',
    detectionGuidance: ['Consistency score declining over time', 'routine_discipline trait weight below 45', 'Creator self-reports fatigue or overwhelm'],
    mitigation: ['Set a sustainable posting cadence', 'Batch content production', 'Schedule regular breaks into the calendar', 'Delegate or template repetitive tasks'],
    coachingGuidance: 'Burnout is the number one career-ender. Treat sustainability as a non-negotiable constraint, not a nice-to-have.',
    relatedArchetypes: ['Soft Girlfriend Experience', 'Nurse', 'Submissive', 'Party Girl', 'Fitness Goddess'],
    relatedTraits: ['routine_discipline', 'risk_awareness'],
    relatedVerticals: ['Cosy Authenticity', 'Fitness Journey', 'Lifestyle Vlogging / GRWM'],
  },
  {
    id: 'risk-002',
    title: 'Boundary erosion',
    description: 'Gradual expansion of content or interaction beyond the creator\'s comfort zone, driven by fan requests or revenue pressure.',
    severity: 'critical',
    detectionGuidance: ['risk_awareness trait weight below 50', 'Authenticity band is Potential Conflict', 'Creator content exceeds stated boundaries'],
    mitigation: ['Document and publish clear boundaries', 'Review boundaries quarterly', 'Build boundary-holding into DM templates', 'Reject requests outside boundaries consistently'],
    coachingGuidance: 'Boundaries are brand assets, not limitations. Fans who push past them are not worth the revenue.',
    relatedArchetypes: ['Submissive', 'Soft Girlfriend Experience', 'Nurse', 'Girl Next Door', 'Single Mom'],
    relatedTraits: ['risk_awareness', 'trust_building'],
    relatedVerticals: ['Cosy Authenticity', 'Confessional Storytime'],
  },
  {
    id: 'risk-003',
    title: 'Privacy and identity exposure',
    description: 'Personal identity, location, or private information leaks through content, metadata, or fan interactions.',
    severity: 'critical',
    detectionGuidance: ['risk_awareness trait weight below 45', 'Content contains identifiable locations or documents', 'Creator uses real name or personal accounts'],
    mitigation: ['Separate personal and creator identities completely', 'Strip metadata from all uploads', 'Use a VPN and separate devices', 'Audit existing content for accidental leaks'],
    coachingGuidance: 'Privacy is irreversible — once exposed, it cannot be undone. Treat this as the highest-priority safety check.',
    relatedArchetypes: ['Single Mom', 'College Girl', 'Country Girl'],
    relatedTraits: ['risk_awareness'],
    relatedVerticals: ['Confessional Storytime', 'Lifestyle Vlogging / GRWM'],
  },
  {
    id: 'risk-004',
    title: 'Emotional dependency dynamics',
    description: 'Fans develop unhealthy attachment that creates pressure, guilt, or safety concerns for the creator.',
    severity: 'high',
    detectionGuidance: ['fan_connection trait weight above 75', 'trust_building trait weight above 70', 'Audience strategy is whales', 'Creator reports feeling obligated to specific fans'],
    mitigation: ['Set clear parasocial expectations in welcome messaging', 'Rotate attention across fans rather than concentrating on individuals', 'Have a protocol for escalating concerning fan behaviour'],
    coachingGuidance: 'Deep connection is a business strength, but dependency is a safety risk. Keep the dynamic professional.',
    relatedArchetypes: ['Soft Girlfriend Experience', 'Submissive', 'Nurse'],
    relatedTraits: ['fan_connection', 'trust_building', 'emotional_familiarity'],
    relatedVerticals: ['Cosy Authenticity'],
  },
  // ── Brand & Positioning ───────────────────────────────────────────────────
  {
    id: 'risk-005',
    title: 'Positioning drift',
    description: 'Brand positioning becomes unclear or inconsistent over time as the creator experiments without a coherent strategy.',
    severity: 'medium',
    detectionGuidance: ['Brand clarity score below 50', 'positioning_clarity trait weight below 45', 'Content themes are scattered across unrelated topics'],
    mitigation: ['Define a positioning statement and review monthly', 'Ensure bio, pinned content, and tone are consistent', 'Experiment within your positioning, not outside it'],
    coachingGuidance: 'Experiments are healthy — but they should orbit your core positioning, not replace it.',
    relatedArchetypes: ['Other', 'Seductress', 'College Girl'],
    relatedTraits: ['positioning_clarity'],
    relatedVerticals: [],
  },
  {
    id: 'risk-006',
    title: 'Authenticity-fantasy mismatch',
    description: 'The marketed persona diverges significantly from the creator\'s authentic comfort zone, causing inconsistency and discomfort.',
    severity: 'high',
    detectionGuidance: ['Authenticity band is Potential Conflict', 'Authenticity flags present', 'Creator expresses discomfort with their positioning'],
    mitigation: ['Audit the gap between persona and authentic self', 'Either adjust positioning toward authenticity or invest in performance skills', 'Seek coaching on sustainable persona management'],
    coachingGuidance: 'A persona you cannot sustain is a ticking clock. Either close the gap or own the performance.',
    relatedArchetypes: ['High-Class Escort Fantasy', 'Corporate Rebel', 'Bimbo', 'Dominatrix'],
    relatedTraits: ['authenticity', 'positioning_clarity', 'risk_awareness'],
    relatedVerticals: ['Roleplay / Character Content'],
  },
  {
    id: 'risk-007',
    title: 'Content saturation in archetype lane',
    description: 'The creator\'s archetype or niche becomes overcrowded, making differentiation difficult and depressing pricing power.',
    severity: 'medium',
    detectionGuidance: ['Archetype is high-frequency (Girl Next Door, Seductress)', 'Brand clarity score below 55', 'Growth is slowing despite consistent output'],
    mitigation: ['Develop a signature hook that differentiates within the lane', 'Combine archetype with a niche interest for specificity', 'Focus on depth of connection over breadth of reach'],
    coachingGuidance: 'In a crowded lane, the creator with the clearest hook wins. Genericism is the enemy.',
    relatedArchetypes: ['Girl Next Door', 'Seductress', 'College Girl', 'Party Girl'],
    relatedTraits: ['positioning_clarity'],
    relatedVerticals: ['Lifestyle Vlogging / GRWM', 'Cosy Authenticity'],
  },
  // ── Commercial & Revenue ──────────────────────────────────────────────────
  {
    id: 'risk-008',
    title: 'Revenue concentration on few fans',
    description: 'A small number of high-spend fans account for a disproportionate share of revenue, creating volatility risk.',
    severity: 'high',
    detectionGuidance: ['Audience strategy is whales', 'Top 3-5 fans account for more than 40% of revenue', 'Creator reports anxiety about losing specific fans'],
    mitigation: ['Diversify revenue across more fans and revenue streams', 'Build mid-tier offers to expand the paying base', 'Avoid custom offers that only one fan would buy'],
    coachingGuidance: 'Whale strategy is powerful, but concentration is fragile. Build a broader base alongside your VIPs.',
    relatedArchetypes: ['Luxury Muse', 'High-Class Escort Fantasy', 'Dominatrix', 'Soft Girlfriend Experience'],
    relatedTraits: ['monetisation_fit'],
    relatedVerticals: [],
  },
  {
    id: 'risk-009',
    title: 'Under-pricing and value leak',
    description: 'Creator prices well below the value they deliver, leaving revenue on the table and attracting low-quality fans.',
    severity: 'medium',
    detectionGuidance: ['Monetisation score below 50', 'monetisation_fit trait weight below 45', 'Creator reports high workload but low revenue'],
    mitigation: ['Benchmark pricing against comparable creators', 'Implement tiered pricing', 'Raise prices gradually with clear value framing', 'Stop giving away premium content for free'],
    coachingGuidance: 'Pricing is positioning. Low prices attract low-value fans and signal low confidence.',
    relatedArchetypes: ['Girl Next Door', 'Country Girl', 'Single Mom', 'College Girl'],
    relatedTraits: ['monetisation_fit', 'positioning_clarity'],
    relatedVerticals: ['Cosy Authenticity'],
  },
  {
    id: 'risk-010',
    title: 'Platform dependency',
    description: 'Over-reliance on a single platform for both discovery and revenue, exposing the business to policy changes or deplatforming.',
    severity: 'high',
    detectionGuidance: ['Creator has no cross-platform presence', 'All revenue comes from one source', 'Archetype has elevated platform-risk'],
    mitigation: ['Establish at least one alternative discovery channel', 'Build an email or contact list you own', 'Diversify across 2+ revenue platforms where feasible'],
    coachingGuidance: 'You do not own your platform. Build assets you control — email list, website, alternative channels.',
    relatedArchetypes: ['Fitness Goddess', 'College Girl', 'High-Class Escort Fantasy'],
    relatedTraits: ['risk_awareness'],
    relatedVerticals: [],
  },
  // ── Content & Production ──────────────────────────────────────────────────
  {
    id: 'risk-011',
    title: 'Content production cost creep',
    description: 'Rising production costs (styling, sets, costumes, equipment) erode margins without proportional revenue growth.',
    severity: 'medium',
    detectionGuidance: ['Archetype requires high production value', 'visual_discipline trait weight above 65', 'Creator reports rising costs'],
    mitigation: ['Track cost per content piece', 'Batch production to reduce per-unit cost', 'Reuse sets, costumes, and props across content', 'Ensure pricing keeps pace with production investment'],
    coachingGuidance: 'Higher production is only worth it if it drives proportionally higher revenue. Track the ratio.',
    relatedArchetypes: ['Luxury Muse', 'Cosplayer', 'Trophy Wife', 'Rich Girl'],
    relatedTraits: ['visual_discipline'],
    relatedVerticals: ['Editorial / High-Fashion Shoots', 'Roleplay / Character Content'],
  },
  {
    id: 'risk-012',
    title: 'Content monotony and format fatigue',
    description: 'Repeating the same content format without variation leads to fan disengagement and declining metrics.',
    severity: 'medium',
    detectionGuidance: ['Content clusters on a single format', 'Engagement metrics declining despite consistent posting', 'Fans stop commenting or interacting'],
    mitigation: ['Introduce at least one complementary content format', 'Rotate themes on a schedule', 'Ask fans what they want to see more of'],
    coachingGuidance: 'Consistency in cadence is essential — consistency in format is a trap. Vary while staying on-brand.',
    relatedArchetypes: ['Fitness Goddess', 'Naughty Librarian', 'Country Girl', 'Spiritual Goddess'],
    relatedTraits: ['routine_discipline'],
    relatedVerticals: ['Fitness Journey', 'Editorial / High-Fashion Shoots'],
  },
  {
    id: 'risk-013',
    title: 'Persona fatigue',
    description: 'Maintaining a character-heavy persona becomes exhausting or feels inauthentic over time, leading to inconsistency.',
    severity: 'medium',
    detectionGuidance: ['Archetype requires sustained character performance', 'authenticity trait weight below 55', 'Creator reports feeling "fake" or drained by the persona'],
    mitigation: ['Build in persona-off content moments (behind-the-scenes, real talk)', 'Evolve the persona gradually to stay authentic', 'Consider a persona that is closer to the authentic self'],
    coachingGuidance: 'A persona should amplify who you are, not replace you. If it is draining, it needs adjustment.',
    relatedArchetypes: ['Dominatrix', 'Hot Teacher', 'Naughty Librarian', 'Corporate Rebel', 'Bimbo'],
    relatedTraits: ['authenticity', 'routine_discipline'],
    relatedVerticals: ['Roleplay / Character Content'],
  },
  // ── Compliance & Safety ───────────────────────────────────────────────────
  {
    id: 'risk-014',
    title: 'Platform terms of service violation',
    description: 'Content, language, or positioning that violates platform TOS, risking account suspension or permanent ban.',
    severity: 'critical',
    detectionGuidance: ['Archetype has elevated compliance sensitivity', 'Content includes edge-case language or themes', 'Creator has received platform warnings'],
    mitigation: ['Audit all content against current platform TOS', 'Review and clean bio, hashtags, and promotional language', 'Avoid compliance-grey content in discoverable/promoted posts'],
    coachingGuidance: 'Platform rules change without notice. Build a compliance review habit, not a one-time audit.',
    relatedArchetypes: ['College Girl', 'High-Class Escort Fantasy', 'Submissive', 'Dominatrix'],
    relatedTraits: ['risk_awareness'],
    relatedVerticals: [],
  },
  {
    id: 'risk-015',
    title: 'Over-disclosure in confessional content',
    description: 'Sharing too much personal information in storytelling content, exposing the creator to privacy, safety, or reputational risk.',
    severity: 'high',
    detectionGuidance: ['Vertical involves confessional or storytime content', 'risk_awareness trait weight below 50', 'Creator shares real names, locations, or identifying details'],
    mitigation: ['Pre-screen stories for identifying information before publishing', 'Change names, locations, and details in all stories', 'Set a personal disclosure limit and review before each post'],
    coachingGuidance: 'The audience wants the emotion, not the data. You can be radically authentic without being identifiable.',
    relatedArchetypes: ['Single Mom', 'Girl Next Door', 'College Girl'],
    relatedTraits: ['authenticity', 'risk_awareness'],
    relatedVerticals: ['Confessional Storytime', 'Polarizing Storytimes'],
  },
  {
    id: 'risk-016',
    title: 'Fan entitlement escalation',
    description: 'High-spend or long-term fans begin demanding content, attention, or access beyond what is offered, testing boundaries.',
    severity: 'high',
    detectionGuidance: ['Audience strategy is whales', 'fan_connection trait weight above 70', 'Creator reports uncomfortable fan demands'],
    mitigation: ['Have a standard response for declining unreasonable requests', 'Enforce boundaries consistently regardless of spend', 'Document and escalate threatening or abusive behaviour'],
    coachingGuidance: 'The most dangerous fan is the one who believes their spending entitles them to more than you offer. Hold firm.',
    relatedArchetypes: ['Soft Girlfriend Experience', 'Submissive', 'Dominatrix', 'Nurse'],
    relatedTraits: ['trust_building', 'risk_awareness', 'fan_connection'],
    relatedVerticals: [],
  },
];

/** Risk map keyed by id for O(1) lookup. */
export const RISK_MAP: Record<string, Risk> = Object.fromEntries(
  RISKS.map(r => [r.id, r])
);
